export const MODAL = "MODAL";

export const MODAL_ISOPEN_REQUEST = "MODAL_ISOPEN_REQUEST";
export const MODAL_ISOPEN_SUCCESS = "MODAL_ISOPEN_SUCCESS";
export const MODAL_ISOPEN_FAIL = "MODAL_ISOPEN_FAIL";

export const TOGGLE_THEME_REQUEST = "TOGGLE_THEME_REQUEST";
export const TOGGLE_THEME_SUCCESS = "TOGGLE_THEME_SUCCESS";
export const TOGGLE_THEME_FAIL = "TOGGLE_THEME_FAIL";
export const TOGGLE_THEME_RESET = "TOGGLE_THEME_RESET";