export const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST'
export const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS'
export const USERS_ADD_FAIL = 'USERS_ADD_FAIL'
export const USERS_ADD_RESET = 'USERS_ADD_RESET'

export const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST'
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS'
export const USERS_DELETE_FAIL = 'USERS_DELETE_FAIL'
export const USERS_DELETE_RESET = 'USERS_DELETE_RESET'

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";